config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :reservations
  resources :vacation_properties
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get "login/", to: "sessions#login", as: "login"
  # get "logout/", to: "sessionslogout"
  # post "login_attempt/", to: "sessions#login_attempt"
  #
  # resources :users, only: [:new, :create, :show]
  #
  # resourses :vacation_properties, path: "/properties"
  # resources :reservations, only: [:new, :create]
  # post "resevervations/incoming", to: "reservations#accept_or_reject", as: "incoming"
  #
  # root "main#index", as: "home"

end

app/models/vacation_property.rb
class VacationProperty < ApplicationRecord
  belongs_to :user #HOST
  has_many :reservations
  has_many :users, through: :reservations #GUESTS
end

app/controllers/vacation_properties_controller.rb
class VacationPropertiesController < ApplicationController
  before_action :set_vacation_property, only: [:show, :edit, :update, :destroy]

  # GET /vacation_properties
  # GET /vacation_properties.json
  def index
    @vacation_properties = VacationProperty.all
  end

  # GET /vacation_properties/1
  # GET /vacation_properties/1.json
  def show
  end

  # GET /vacation_properties/new
  def new
    @vacation_property = VacationProperty.new
  end

  # GET /vacation_properties/1/edit
  def edit
  end

  # POST /vacation_properties
  # POST /vacation_properties.json
  def create
    @vacation_property = VacationProperty.new(vacation_property_params)

    respond_to do |format|
      if @vacation_property.save
        format.html { redirect_to @vacation_property, notice: 'Vacation property was successfully created.' }
        format.json { render :show, status: :created, location: @vacation_property }
      else
        format.html { render :new }
        format.json { render json: @vacation_property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vacation_properties/1
  # PATCH/PUT /vacation_properties/1.json
  def update
    respond_to do |format|
      if @vacation_property.update(vacation_property_params)
        format.html { redirect_to @vacation_property, notice: 'Vacation property was successfully updated.' }
        format.json { render :show, status: :ok, location: @vacation_property }
      else
        format.html { render :edit }
        format.json { render json: @vacation_property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vacation_properties/1
  # DELETE /vacation_properties/1.json
  def destroy
    @vacation_property.destroy
    respond_to do |format|
      format.html { redirect_to vacation_properties_url, notice: 'Vacation property was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vacation_property
      @vacation_property = VacationProperty.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vacation_property_params
      params.require(:vacation_property).permit(:description, :image_url)
    end
end

app/helpers/vacation_properties_helper.rb
module VacationPropertiesHelper
end

app/views/vacation_properties/_form.html.erb
<%= form_for(vacation_property) do |f| %>
  <% if vacation_property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vacation_property.errors.count, "error") %> prohibited this vacation_property from being saved:</h2>

      <ul>
      <% vacation_property.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :image_url %>
    <%= f.text_field :image_url %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vacation_properties/edit.html.erb
<h1>Editing Vacation Property</h1>

<%= render 'form', vacation_property: @vacation_property %>

<%= link_to 'Show', @vacation_property %> |
<%= link_to 'Back', vacation_properties_path %>

app/views/vacation_properties/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vacation Properties</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Image url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vacation_properties.each do |vacation_property| %>
      <tr>
        <td><%= vacation_property.description %></td>
        <td><%= vacation_property.image_url %></td>
        <td><%= link_to 'Show', vacation_property %></td>
        <td><%= link_to 'Edit', edit_vacation_property_path(vacation_property) %></td>
        <td><%= link_to 'Destroy', vacation_property, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vacation Property', new_vacation_property_path %>

app/views/vacation_properties/new.html.erb
<h1>New Vacation Property</h1>

<%= render 'form', vacation_property: @vacation_property %>

<%= link_to 'Back', vacation_properties_path %>

app/views/vacation_properties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @vacation_property.description %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @vacation_property.image_url %>
</p>

<%= link_to 'Edit', edit_vacation_property_path(@vacation_property) %> |
<%= link_to 'Back', vacation_properties_path %>