config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :reservations
  resources :vacation_properties
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get "login/", to: "sessions#login", as: "login"
  # get "logout/", to: "sessionslogout"
  # post "login_attempt/", to: "sessions#login_attempt"
  #
  # resources :users, only: [:new, :create, :show]
  #
  # resourses :vacation_properties, path: "/properties"
  # resources :reservations, only: [:new, :create]
  # post "resevervations/incoming", to: "reservations#accept_or_reject", as: "incoming"
  #
  # root "main#index", as: "home"

end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :vacation_property
  belongs_to :user

  validates :name, presence: true
  validates :phone_number, presence: true

  enum status: [:pending, :confirmed, :rejected]

  def notify_host(force=false)
    @host = User.find(self.vacation_property[:user_id])

    #DON'T SEND THE MESSAGE IF WE HAVE MORE THAN ONE OR WE AREN'T BEING FORCED
    if @host.pending_reservations.length > 1 or !force
      return
    else
      message = "You have a new reservation request from #{self.name} for #{self.vacation_property.description}:

      '#{self.message}'

      Reply [accept] or [reject]."

      @host.send_message_via_sms(message)
    end
  end

  def confirm!
    self.status = "confirmed"
    self.save!
  end

  def reject!
    self.status = "rejected"
    self.save!
  end

  def notify_guest
    @guest = User.find_by(phone_number: self.phone_number)

    if self.status_changed? && (self.status == "confirmed" || self.status == "rejected")
      message = "Your recent request to stay at #{self.vacation_property.description} was #{self.status}."
      @guest.send_message_via_sms(message)
    end
  end

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: [:show, :edit, :update, :destroy]

  # GET /reservations
  # GET /reservations.json
  def index
    @reservations = Reservation.all
  end

  # GET /reservations/1
  # GET /reservations/1.json
  def show
  end

  # GET /reservations/new
  def new
    @reservation = Reservation.new
  end

  # GET /reservations/1/edit
  def edit
  end

  # POST /reservations
  # POST /reservations.json
  def create
    @vacation_property = VacationProperty.find(params[:reservation][:property_id])
    @reservation = @vacation_property.reservations.create(reservation_params)

    if @reservation.save
      flash[:notice] = "Sending your reservation request now."
      @reservation.notify_host
      redirect_to @vacation_property
    else
      flash[:danger] = @reservation.errors
    end
  end

# WEBHOOK FOR TWILIO INCOMING MESSAGE FROM HOST
  def accept_or_reject
    incoming = Santize.clean(params[:From]).gsub(/^\+\d/, '')
    sms_input = params[:Body].downcase
    begin
      @host = User.find_by(phone_number: incoming)
      @reservation = @host.pending_reservation

      if sms_input == "accept" || sms_input == "yes"
        @reservation.confirm!
      else
        @reservation.reject!
      end

      @host.check_for_reservations_pending

      sms_response = "You have successfully #{@reservation.status} the reservation."
      respond(sms_response)
    rescue
      sms_response = "Sorry, it looks like you don't have any reservations to respond to"
      respond(sms_response)
    end
  end

  # PATCH/PUT /reservations/1
  # PATCH/PUT /reservations/1.json
  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to @reservation, notice: 'Reservation was successfully updated.' }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1
  # DELETE /reservations/1.json
  def destroy
    @reservation.destroy
    respond_to do |format|
      format.html { redirect_to reservations_url, notice: 'Reservation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # SEND AN SMS BACK TO THE SUBSCRIBER
  def respond(message)
    response = Twilio::TwiML::Response.new do |r|
      r.Message message
    end
    render text: response.text
  end

  # NEVER TRUST PARAMETERS FROM THE SCARY INTERNET, ONLY ALLOW THE WHITE LIST THROUGH
  def reservation_params
    params.require(:reservation).permit(:name, :phone_number, :message)
  end


  # Use callbacks to share common setup or constraints between actions.
  def set_reservation
    @reservation = Reservation.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def reservation_params
    params.require(:reservation).permit(:name, :phone_number, :vacation_property_id, :user_id, :status)
  end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_form.html.erb
<%= form_for(reservation) do |f| %>
  <% if reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
      <% reservation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :phone_number %>
    <%= f.text_field :phone_number %>
  </div>

  <div class="field">
    <%= f.label :vacation_property_id %>
    <%= f.text_field :vacation_property_id %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :status %>
    <%= f.number_field :status %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reservations/edit.html.erb
<h1>Editing Reservation</h1>

<%= render 'form', reservation: @reservation %>

<%= link_to 'Show', @reservation %> |
<%= link_to 'Back', reservations_path %>

app/views/reservations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reservations</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone number</th>
      <th>Vacation property</th>
      <th>User</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reservations.each do |reservation| %>
      <tr>
        <td><%= reservation.name %></td>
        <td><%= reservation.phone_number %></td>
        <td><%= reservation.vacation_property %></td>
        <td><%= reservation.user %></td>
        <td><%= reservation.status %></td>
        <td><%= link_to 'Show', reservation %></td>
        <td><%= link_to 'Edit', edit_reservation_path(reservation) %></td>
        <td><%= link_to 'Destroy', reservation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reservation', new_reservation_path %>

app/views/reservations/new.html.erb
<h1>New Reservation</h1>

<%= render 'form', reservation: @reservation %>

<%= link_to 'Back', reservations_path %>

app/views/reservations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @reservation.name %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @reservation.phone_number %>
</p>

<p>
  <strong>Vacation property:</strong>
  <%= @reservation.vacation_property %>
</p>

<p>
  <strong>User:</strong>
  <%= @reservation.user %>
</p>

<p>
  <strong>Status:</strong>
  <%= @reservation.status %>
</p>

<%= link_to 'Edit', edit_reservation_path(@reservation) %> |
<%= link_to 'Back', reservations_path %>